### ISSUE TITLE
Feature Request: a way to globally toggle the ruler

### ISSUE THREAD

**Issue by noahadvs** [orentrutner/reading-ruler#12]
I wish I could globally toggle the ruler with one click or with a keyboard shortcut instead of having to open a popup and disable it for the page or website. I usually only want the ruler when doing a lot of reading and I want to disable it the rest of the time. When I do a lot of reading, it's usually not very dependent on the specific websites I'm looking at.

**Comment by orentrutner** [comment]
That’s likely the most asked feature request to date. I’ll take a look at adding a global switch.

**Comment by orentrutner** [comment]
Done! Fixed by commits 0db470d90996797b00a1f8ea3d1f8f08366d9566 (toggle) df61ebba7fa59cea85225b148e5f9e0331322395 (shortcut).
