### ISSUE TITLE
Hotkey not working

### ISSUE THREAD

**Issue by LAsGrandeFish** [orentrutner/reading-ruler#20]
The _alt + R_ hotkey has not been working for me. I have tried disabling it on and off as well as removing the extension and adding it back but have not had any luck with it. Are there any other troubling shooting tips for this?

**Comment by orentrutner** [comment]
Sorry to hear the hotkey is not working for you! Maybe I can help t-shoot:
1. Does toggling the extension from the icon menu work? (If yes, that means the on/off code path works, and will rule out a large group of possible bugs)
2. Does the Firefox Manage Extension Shortcuts page list Alt+R as an extension for reading ruler? https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox for how to get there. (If yes, at least we know that reading-ruler registered the shortcut correctly with Firefox)
3. If the Manage Extension Shortcuts page does list Alt+R, can you experiment with replacing it with a different shortcut? Does that work?
4. If none of those help, would you mind sharing the OS (and its version), the Firefox version, the language (if not US English) and the keyboard language (also, if not US English). I don't have an obvious path from those to a problem with the hotkey, but it may help me narrow down the possibilities.

**Comment by orentrutner** [comment]
I haven't heard back -- I'll close this. Please go ahead and resubmit if this is still an issue for you. Thanks!
